### ISSUE TITLE
Publish tA Volume 1

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/QuarterlyObjectives#6]
Completed when tA is available in:

* [x] Published into tD https://github.com/unfoldingWord-dev/translationDatabaseWeb/issues/68
* [x] ~~Word https://github.com/unfoldingWord-dev/Door43/issues/317~~
* [x] PDF https://github.com/unfoldingWord-dev/Door43/issues/96
* [x] tS https://github.com/unfoldingWord-dev/ts-android/issues/549
* [x] Web draft https://github.com/unfoldingWord/unfoldingWord.github.io/issues/98
* [x] Web final https://github.com/unfoldingWord/unfoldingWord.github.io/issues/105
* [x] ~~Suck into Help Desk https://github.com/unfoldingWord-dev/Door43/issues/344~~
* [x] ~~Available to be configured for translation in Door43 https://github.com/unfoldingWord-dev/Door43/issues/59~~
